version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mc1098
      - POSTGRES_DB=videogame-player
    ports:
      - "5432:5432"
  app:
    image: 'camila1098/videojuego-jugador:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/videogame-player
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mc1098
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "6090:6090"
